---
- hosts: atlas.artemit.mgmt
  remote_user: ansible
  become: yes
  become_user: root
  become_method: sudo
  vars:
    interfaces:
     - name: enp4s0
       address: 192.168.2.1
       prefix: 24
       netmask: 255.255.255.0
       gateway: 192.168.2.254
       dns1: 192.168.2.4
       zone: management
    team:
     - name: team0
       address: 192.168.5.1
       prefix: 24
       netmask: 255.255.255.0
       zone: storage
    team_slaves:
     - name: enp2s0
       master: team0
       priority: 100
       zone: storage
     - name: enp3s0
       master: team0
       priority: 100
       zone: storage

  tasks:
  - name: configure interfaces
    template: src=./network_templates/ifcfg-eth.j2 dest=/etc/sysconfig/network-scripts/ifcfg-{{ item.name }} owner=root group=root mode="u=rw,g=r,o=r"
    with_items: "{{interfaces}}"
  - name: configure teams
    template: src=./network_templates/ifcfg-team.j2 dest=/etc/sysconfig/network-scripts/ifcfg-{{ item.name }} owner=root group=root mode="u=rw,g=r,o=r"
    with_items: "{{team}}"
  - name: configure team slaves
    template: src=./network_templates/ifcfg-team-slave.j2 dest=/etc/sysconfig/network-scripts/ifcfg-{{ item.name }} owner=root group=root mode="u=rw,g=r,o=r"
    with_items: "{{team_slaves}}"
  - name: restart network service
    service: name=network state=restarted

