---
- hosts: one_servers
  remote_user: ansible
  become: yes
  become_user: root
  become_method: sudo
  tasks: 
    - name: Allow users from specific addresses
      lineinfile: dest=/etc/ssh/sshd_config
                  regexp="^AllowUsers"
                  line="AllowUsers artemit@192.168.1.200 ansible@192.168.1.200 ansible@192.168.2.4 oneadmin@192.168.2.4"
                  state=present

    - name: SSH service must be restarted
      service: name=sshd state=restarted

- hosts: jano.artemit.mgmt
  remote_user: ansible
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Add remote keys to known hosts file
      shell: ssh-keyscan {{ item }} >> /var/lib/one/.ssh/known_hosts
      with_items: "{{ groups.one_worker_nodes }}"

    - name: Change known_hosts file permissions
      file: path=/var/lib/one/.ssh/known_hosts owner=oneadmin group=oneadmin mode=0600
